# Generated by Django 3.1.2 on 2020-10-10 03:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('published_at', models.DateTimeField()),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=100), blank=True, null=True, size=None)),
                ('channelTitle', models.CharField(max_length=100)),
            ],
        ),
    ]
